package io.yosemitekids.app

import io.yosemitekids.app.data.AiScreener
import io.yosemitekids.app.data.Captions
import io.yosemitekids.app.data.ScreeningStore
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder
import java.io.File

/**
 * The pre-play deep check judges what the batch pass can't see: description,
 * tags and the transcript. These tests pin the transcript flattening (cue
 * noise must never read as spoken words), the prompt payload, and the store
 * rules that make a deep verdict stick — deep beats shallow, never the
 * other way around.
 */
class DeepCheckTest {

    @get:Rule
    val tmp = TemporaryFolder()

    // --- caption flattening ---------------------------------------------------

    @Test
    fun `vtt cues flatten to text without timings or tags`() {
        val vtt = """
            WEBVTT
            Kind: captions

            00:00.000 --> 00:02.500
            <c>Hello</c> and welcome

            00:02.500 --> 00:05.000
            to the show
        """.trimIndent()
        assertEquals("Hello and welcome\nto the show", Captions.toPlainText(vtt))
    }

    @Test
    fun `rolling auto-caption repeats collapse`() {
        val vtt = """
            WEBVTT

            00:00.000 --> 00:02.000
            we built a volcano

            00:02.000 --> 00:04.000
            we built a volcano
            out of baking soda
        """.trimIndent()
        assertEquals(
            "we built a volcano\nout of baking soda",
            Captions.toPlainText(vtt)
        )
    }

    @Test
    fun `srt counters and timing lines are dropped`() {
        val srt = """
            1
            00:00:00,000 --> 00:00:02,000
            First line

            2
            00:00:02,000 --> 00:00:04,000
            Second line
        """.trimIndent()
        assertEquals("First line\nSecond line", Captions.toPlainText(srt))
    }

    @Test
    fun `ttml paragraphs flatten with entities decoded`() {
        val ttml = """
            <?xml version="1.0" encoding="utf-8"?>
            <tt xmlns="http://www.w3.org/ns/ttml"><body><div>
            <p begin="0s" end="2s">Tom &amp; Jerry<br/>are back</p>
            <p begin="2s" end="4s">it&#39;s fun</p>
            </div></body></tt>
        """.trimIndent()
        assertEquals("Tom & Jerry\nare back\nit's fun", Captions.toPlainText(ttml))
    }

    @Test
    fun `english track wins and prefers the human-authored sort order`() {
        fun sub(lang: String, auto: Boolean) = io.yosemitekids.app.data.YouTubeRepository.Subtitle(
            url = "u", mimeType = "text/vtt", languageTag = lang, name = lang, autoGenerated = auto
        )
        // subtitlesOf sorts human tracks first — pickEnglish trusts that order.
        val subs = listOf(sub("de", false), sub("en-US", false), sub("en", true))
        assertEquals("en-US", Captions.pickEnglish(subs)?.languageTag)
        assertEquals(null, Captions.pickEnglish(listOf(sub("de", false), sub("fr", true))))
    }

    // --- transcript clipping --------------------------------------------------

    @Test
    fun `clip keeps head and tail with a marker between`() {
        val text = "a".repeat(10_000) + "MIDDLE" + "z".repeat(10_000)
        val clipped = AiScreener.clipTranscript(text, maxChars = 1_000)
        assertTrue(clipped.startsWith("a"))
        assertTrue(clipped.endsWith("z"))
        assertTrue("omitted" in clipped)
        assertFalse("MIDDLE" in clipped)
        // Never grows past the cap by more than the marker line.
        assertTrue(clipped.length < 1_100)
        val short = "short transcript"
        assertEquals(short, AiScreener.clipTranscript(short, maxChars = 1_000))
    }

    // --- prompt payload -------------------------------------------------------

    @Test
    fun `deep user prompt carries the fields and marks a missing transcript`() {
        val with = JSONObject(AiScreener.deepUserPrompt(
            "vid123", "Title", "Chan", "desc", listOf("t1", "t2"), "spoken words"
        ))
        assertEquals("vid123", with.getString("id"))
        assertEquals("desc", with.getString("description"))
        assertEquals(2, with.getJSONArray("tags").length())
        assertEquals("spoken words", with.getString("transcript"))

        val without = JSONObject(AiScreener.deepUserPrompt(
            "vid123", "Title", "Chan", "", emptyList(), null
        ))
        // No captions is an expected state — the model is told to judge on the
        // rest, not left to guess why the field is missing.
        assertTrue("judge by" in without.getString("transcript"))
        assertFalse(without.has("description"))
        assertFalse(without.has("tags"))
    }

    @Test
    fun `deep reply parses through the shared verdict contract`() {
        val reply = """{"verdicts":[{"id":"vid123","v":"block","why":"scary themes"}]}"""
        val r = AiScreener.parseVerdicts(reply, setOf("vid123")).single()
        assertEquals(AiScreener.Verdict.BLOCK, r.verdict)
        assertEquals("scary themes", r.reason)
    }

    // --- deep verdicts in the store -------------------------------------------

    private fun entry(deep: Boolean, verdict: AiScreener.Verdict, rv: Int = 1) =
        ScreeningStore.Entry(
            verdict = verdict, reason = "r", title = "t", channel = "c",
            thumb = null, rulesVersion = rv, at = 1L, deep = deep
        )

    @Test
    fun `deep flag survives a reload`() {
        val file = File(tmp.root, "screening.json")
        ScreeningStore(file).putAll(mapOf("vid" to entry(deep = true, verdict = AiScreener.Verdict.BLOCK)))
        val reread = ScreeningStore(file).get("vid")
        assertEquals(true, reread?.deep)
        assertEquals(AiScreener.Verdict.BLOCK, reread?.verdict)
    }

    @Test
    fun `peer deep verdict replaces a shallow one but never the reverse`() {
        val store = ScreeningStore(File(tmp.root, "screening.json"))
        store.putAll(mapOf("vid" to entry(deep = false, verdict = AiScreener.Verdict.ALLOW)))

        val deepPeer = ScreeningStore(File(tmp.root, "deep-peer.json"))
        deepPeer.putAll(mapOf("vid" to entry(deep = true, verdict = AiScreener.Verdict.BLOCK)))
        assertEquals(1, store.importJson(deepPeer.exportJson(1), 1))
        assertEquals(AiScreener.Verdict.BLOCK, store.get("vid")?.verdict)
        assertEquals(true, store.get("vid")?.deep)

        // A later shallow (or equal-deep) peer verdict must not roll it back.
        val shallowPeer = ScreeningStore(File(tmp.root, "shallow-peer.json"))
        shallowPeer.putAll(mapOf("vid" to entry(deep = false, verdict = AiScreener.Verdict.ALLOW)))
        assertEquals(0, store.importJson(shallowPeer.exportJson(1), 1))
        assertEquals(AiScreener.Verdict.BLOCK, store.get("vid")?.verdict)
    }
}
