plugins {
    alias(libs.plugins.kotlin.jvm)
    application
}

// The always-on peer.
//
// Not a new architecture: it speaks the same routes a TV speaks and takes part
// in the same merge, using the *same* `:core` code the app does. What it adds
// is that it never sleeps, so two parents reconcile without both being home.
//
// It does NOT yet feed the TVs. A TV has no way to join a hub — the join
// screen exists only in the phone settings — and a TV never initiates sync in
// the first place. Until that lands the hub is a rendezvous between parents,
// not a server for the televisions. See "Next up" in docs/FORK-NOTES.md.
//
// A household that never runs this sees no change at all. That is a hard rule:
// every route here already exists, and nothing in :app may come to depend on
// the hub being present.

kotlin {
    jvmToolchain(17)
}

application {
    mainClass.set("io.yosemitekids.hub.MainKt")
}

// The version this image was built from, so anything talking to a hub can ask
// which one it is.
//
// WHY THIS EXISTS AT ALL. The hub is a relay, never an authority — but
// `HubStore.edit` round-trips the document through `ConfigJson.toJson` on
// every admin save, and `toJson` writes the fields THIS build models. So a
// container left on an old image does not merely lack a new control: it
// silently drops the key backing it out of the family's config the first time
// a parent saves anything on the NAS. Config fields ride a two-release gate
// precisely so that window is survivable, and until now nothing could check
// which side of the gate a given hub was on. `GET /health` now says, before
// any credential is presented, which is what lets that be *detected* rather
// than discovered.
//
// Kept equal to the app's `versionName` by guard 39 in scripts/check.*, and
// that is the point rather than an inconvenience: the two-release gate is
// counted in the project's releases, so the hub has to be numbered in them
// too. It also keeps the published image honest — bumping this is a change
// under hub/, which is what .github/workflows/hub-image.yml watches, so a
// release rebuilds the image instead of leaving it advertising the version
// before it.
//
// The app reads its own from BuildConfig; a plain JVM module has none, so it
// is generated here — the same idiom :crawl uses for ExtractorVersion.
val hubVersion = "1.2.0"
val generatedDir = layout.buildDirectory.dir("generated/hubVersion")
val generateHubBuild by tasks.registering {
    inputs.property("version", hubVersion)
    outputs.dir(generatedDir)
    doLast {
        val out = generatedDir.get().file("io/yosemitekids/hub/HubBuild.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            """
            |package io.yosemitekids.hub
            |
            |/** Generated by hub/build.gradle.kts. Do not edit. */
            |object HubBuild {
            |    const val VERSION = "$hubVersion"
            |}
            |""".trimMargin()
        )
    }
}
sourceSets.main {
    kotlin.srcDir(generatedDir)
}
tasks.named("compileKotlin") { dependsOn(generateHubBuild) }

dependencies {
    // The merge, the stamper, the serializers — shared verbatim with the app so
    // there is one implementation of the rules rather than two that drift.
    implementation(project(":core"))
    // The crawler and the search index: the hub builds the index the phone
    // used to build alone (docs/PLAN-crawl.md).
    implementation(project(":crawl"))
    // Android supplies org.json in the platform; here it has to be brought.
    implementation(libs.json)

    testImplementation(libs.json)
    testImplementation("junit:junit:4.13.2")
}

tasks.test {
    useJUnit()
}
