plugins {
    alias(libs.plugins.kotlin.jvm)
}

// The one crawler, for the phone, the TV and the Docker hub.
//
// NewPipeExtractor, the HTTP layer it needs, the per-channel search index and
// the crawl loop live here so the hub can build the index the phone used to
// build alone (docs/PLAN-crawl.md). Plain JVM like :core, and guarded the
// same way: the moment this module imports Android the hub cannot build it.
//
// Not part of :core on purpose. :core's contract is "no disk, no clock" and
// the crawl is both — network, files, timestamps — so it gets a module whose
// contract says so, and :core stays the pure rules.

kotlin {
    jvmToolchain(17)
}

// The extractor version the crawl cursors are stamped with. A persisted
// NewPipe Page is readable only by the extractor version that wrote it, and
// the extractor only changes when this dependency does — sourced from the
// catalog so the stamp can never drift from the actual library. The app used
// to carry this in BuildConfig; the hub has no BuildConfig, so it is generated
// here for both.
val extractorVersion = libs.versions.newpipeextractor.get()
val generatedDir = layout.buildDirectory.dir("generated/extractorVersion")
val generateExtractorVersion by tasks.registering {
    inputs.property("version", extractorVersion)
    outputs.dir(generatedDir)
    doLast {
        val out = generatedDir.get().file("io/yosemitekids/app/data/ExtractorVersion.kt").asFile
        out.parentFile.mkdirs()
        out.writeText(
            """
            |package io.yosemitekids.app.data
            |
            |/** Generated by crawl/build.gradle.kts from gradle/libs.versions.toml. Do not edit. */
            |object ExtractorVersion {
            |    const val VALUE = "$extractorVersion"
            |}
            |""".trimMargin()
        )
    }
}
sourceSets.main {
    kotlin.srcDir(generatedDir)
}
tasks.named("compileKotlin") { dependsOn(generateExtractorVersion) }

dependencies {
    implementation(project(":core"))
    // api, not implementation: the app and the hub both type against
    // NewPipe's Page/StreamInfoItem and OkHttp's client directly.
    api(libs.newpipeextractor)
    api(libs.okhttp)
    api(libs.okhttp.dnsoverhttps)
    api(libs.kotlinx.coroutines.core)
    // compileOnly for the same reason as :core: Android ships org.json.
    compileOnly(libs.json)

    testImplementation(libs.json)
    testImplementation("junit:junit:4.13.2")
}

tasks.test {
    useJUnit()
}

